return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'neovim/nvim-lspconfig'
  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
  use 'hrsh7th/nvim-compe'
  use 'hrsh7th/vim-vsnip'
  use 'hrsh7th/vim-vsnip-integ'
  use 'rafamadriz/friendly-snippets'
  use 'windwp/nvim-ts-autotag'
  use 'mhinz/vim-startify'
  use 'romgrk/barbar.nvim'
  use 'editorconfig/editorconfig-vim'
  use 'junegunn/fzf' 
  use 'junegunn/fzf.vim'
  use 'jiangmiao/auto-pairs'
  use 'tpope/vim-surround'
  use 'tpope/vim-commentary'
  use 'tpope/vim-repeat'
  -- use 'tpope/vim-eunuch'
  use 'numtostr/FTerm.nvim'
  use 'kyazdani42/nvim-web-devicons'
  use 'kyazdani42/nvim-tree.lua'
  use 'onsails/lspkind-nvim'
  use 'hoob3rt/lualine.nvim'
  use 'navarasu/onedark.nvim'
  use 'mhartington/formatter.nvim'
  -- use 'joshdick/onedark.vim'
end)
